In [72]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#폰트 설정 (Windows 기본 폰트: 맑은 고딕)
plt.rcParams.update({
    "font.family": "Malgun Gothic",  # 윈도우 기본 한글 폰트
    "font.size": 10,
    "axes.unicode_minus": False,     # 마이너스 깨짐 방지
})

과제 1: Iris 3-class 분류
3개 붓꽃 종류 모두 분류하기

→ LogisticRegression(multi_class='ovr')

In [73]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [74]:
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [75]:
X_1 = iris.data[:,:2]  # 예시로 꽃받침 길이/너비만 사용
y_1 = iris.target

In [76]:
X_1

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [5. , 3.4],
       [4.4, 2.9],
       [4.9, 3.1],
       [5.4, 3.7],
       [4.8, 3.4],
       [4.8, 3. ],
       [4.3, 3. ],
       [5.8, 4. ],
       [5.7, 4.4],
       [5.4, 3.9],
       [5.1, 3.5],
       [5.7, 3.8],
       [5.1, 3.8],
       [5.4, 3.4],
       [5.1, 3.7],
       [4.6, 3.6],
       [5.1, 3.3],
       [4.8, 3.4],
       [5. , 3. ],
       [5. , 3.4],
       [5.2, 3.5],
       [5.2, 3.4],
       [4.7, 3.2],
       [4.8, 3.1],
       [5.4, 3.4],
       [5.2, 4.1],
       [5.5, 4.2],
       [4.9, 3.1],
       [5. , 3.2],
       [5.5, 3.5],
       [4.9, 3.6],
       [4.4, 3. ],
       [5.1, 3.4],
       [5. , 3.5],
       [4.5, 2.3],
       [4.4, 3.2],
       [5. , 3.5],
       [5.1, 3.8],
       [4.8, 3. ],
       [5.1, 3.8],
       [4.6, 3.2],
       [5.3, 3.7],
       [5. , 3.3],
       [7. , 3.2],
       [6.4, 3.2],
       [6.9,

In [77]:
y_1 # 0, 1, 2 3가지가 나옴

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [78]:
X_1_train, X_1_test, y_1_train, y_1_test = train_test_split(X_1,y_1, test_size=0.2, random_state=42)

In [79]:
model = LogisticRegression(multi_class='ovr')
model.fit(X_1_train, y_1_train)

c:\Users\USER\anaconda3\envs\myenv\Lib\site-packages\sklearn\linear_model\_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr')

In [80]:
y_1_pred = model.predict(X_1_test)
y_1_proba = model.predict_proba(X_1_test)

In [81]:
print(y_1_pred[:10])

[1 0 2 1 2 0 1 2 1 1]


In [82]:
print(y_1_proba[:5])
# 0일확률 1일확률 2일확률

[[3.70165763e-02 5.08007777e-01 4.54975647e-01]
 [7.57155306e-01 8.44564141e-02 1.58388280e-01]
 [7.74628183e-05 4.03313318e-01 5.96609220e-01]
 [7.38810105e-02 4.93851517e-01 4.32267473e-01]
 [3.06163334e-03 3.98655072e-01 5.98283295e-01]]


In [83]:
import pandas as pd
proba_df = pd.DataFrame(y_1_proba, columns=['0확률', '1확률', '2확률'])
print(proba_df.round(2))


     0확률   1확률   2확률
0   0.04  0.51  0.45
1   0.76  0.08  0.16
2   0.00  0.40  0.60
3   0.07  0.49  0.43
4   0.00  0.40  0.60
5   0.71  0.18  0.12
6   0.24  0.50  0.26
7   0.01  0.31  0.68
8   0.00  0.58  0.42
9   0.07  0.59  0.34
10  0.04  0.32  0.64
11  0.70  0.26  0.04
12  0.71  0.15  0.13
13  0.72  0.23  0.05
14  0.89  0.07  0.05
15  0.10  0.31  0.59
16  0.02  0.38  0.60
17  0.07  0.67  0.26
18  0.14  0.56  0.30
19  0.01  0.45  0.53
20  0.79  0.18  0.03
21  0.07  0.44  0.48
22  0.81  0.14  0.05
23  0.01  0.45  0.53
24  0.00  0.11  0.89
25  0.01  0.36  0.63
26  0.00  0.47  0.53
27  0.01  0.29  0.70
28  0.70  0.26  0.04
29  0.74  0.22  0.04


In [84]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix, roc_auc_score
# 정확도 : 전체 예측 중에서 정답을 맞춘 비율
# 정밀도 : 모델이 '맞다고 예측한 것' 중 실제로 맞은 비율 (False Positive가 적을수록 높음)
# 재현율 : 실제로 맞는 데이터 중에서 모델이 잘 찾아낸 비율 (False Negative가 적을수록 높음)
# F1 점수: 정밀도와 재현율의 조화 평균 — 두 지표의 균형을 봄
# ROC AUC 점수: 확률 기반 평가 — 클래스들을 얼마나 잘 구분하는지 (1에 가까울수록 좋음)


print("정확도(Accuracy):", accuracy_score(y_1_test, y_1_pred))
print("정밀도(Precision):", precision_score(y_1_test, y_1_pred, average='macro'))
print("재현율(Recall):", recall_score(y_1_test, y_1_pred, average='macro'))
print("F1 점수:", f1_score(y_1_test, y_1_pred, average='macro'))
print("ROC AUC 점수:", round( roc_auc_score(y_1_test, y_1_proba, multi_class='ovr'), 3))

# average='macro' 클래스가 여러 개인 경우, 각 클래스의 점수를 평균내서 계산한다는 뜻

정확도(Accuracy): 0.9333333333333333
정밀도(Precision): 0.9487179487179488
재현율(Recall): 0.9259259259259259
F1 점수: 0.9305555555555555
ROC AUC 점수: 0.961


과제 2: 타이타닉 생존자 분류 / roc_score 가장 높은사람.

In [85]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
import seaborn as sns

In [86]:
titanic = sns.load_dataset("titanic")
titanic.head()

# 생존여부  객실등급    성별    나이    형제배우자수    부모자녀수  운임    탑승항구    객실등급    사람구분    성인남성여부    선실구역    탑승도시    생존여부    혼자승선여부


survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [87]:
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [88]:
titanic.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [89]:
for col in titanic.select_dtypes(include='object').columns:
    print(f"\n▶ {col}")
    print(titanic[col].value_counts(dropna=False))

'''
[sex] male : 0 / female : 1
[embarked] S : 0 / C : 1 / Q : 2 / NaN : -> S (최빈값으로 넣기로함)
[who] man : 0 / woman : 1 / child : 2  -> 성별과 겹처서 그냥 제거
[embark_town] -> embarked과 비슷해서 제거
[alive] -> survive 가 남아있어 제거
이런식으로 정리

'''



▶ sex
sex
male      577
female    314
Name: count, dtype: int64

▶ embarked
embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

▶ who
who
man      537
woman    271
child     83
Name: count, dtype: int64

▶ embark_town
embark_town
Southampton    644
Cherbourg      168
Queenstown      77
NaN              2
Name: count, dtype: int64

▶ alive
alive
no     549
yes    342
Name: count, dtype: int64


'\n[sex] male : 0 / female : 1\n[embarked] S : 0 / C : 1 / Q : 2 / NaN : -> S (최빈값으로 넣기로함)\n[who] man : 0 / woman : 1 / child : 2  -> 성별과 겹처서 그냥 제거\n[embark_town] -> embarked과 비슷해서 제거\n[alive] -> survive 가 남아있어 제거\n이런식으로 정리\n\n'

In [90]:
# 결측치 처리
titanic['embarked'].fillna('S', inplace=True)
#titanic['age'].fillna(titanic['age'].median(), inplace=True)
titanic['age'] = titanic.groupby(['pclass', 'sex'])['age'].transform(
    lambda x: x.fillna(x.median())
)

C:\Users\USER\AppData\Local\Temp\ipykernel_54244\2652717994.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic['embarked'].fillna('S', inplace=True)


In [91]:
# 문자 → 숫자 인코딩
titanic['sex'] = titanic['sex'].map({'male': 0, 'female': 1})
titanic['embarked'] = titanic['embarked'].map({'S': 1, 'C': 2, 'Q': 3})
#titanic['adult_male'] = titanic['adult_male'].map({False: 0, True: 1}).fillna(0).astype(int)
titanic['alone'] = titanic['alone'].map({False: 0, True: 1}).fillna(0).astype(int)

In [92]:
# 한번에 수치형으로 바꾸는 방법(강사님 방법)
# from sklearn.preprocessing import LabelEncoder

# cols = ['who', 'embarked', 'deck']

# for col in cols:
#     le = LabelEncoder()
#     df_t[col] = le.fit_transform(df_t[col].astype(str))


In [93]:
# 파생변수 생성 가족크기
titanic['family_size'] = titanic['sibsp'] + titanic['parch'] + 1

In [94]:
# 불필요한 칼럼 제거
titanic.drop(['who', 'embark_town', 'alive','deck','class','sibsp','parch','adult_male'], axis=1, inplace=True)

In [95]:
titanic.head()

survived  pclass  sex   age     fare  embarked  alone  family_size
0         0       3    0  22.0   7.2500         1      0            2
1         1       1    1  38.0  71.2833         2      0            2
2         1       3    1  26.0   7.9250         1      1            1
3         1       1    1  35.0  53.1000         1      0            2
4         0       3    0  35.0   8.0500         1      1            1

In [96]:
titanic.isnull().sum()

survived       0
pclass         0
sex            0
age            0
fare           0
embarked       0
alone          0
family_size    0
dtype: int64

In [97]:
# 데이터 분리
X = titanic.drop("survived", axis=1)
y = titanic["survived"]

In [103]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [99]:
#model = LogisticRegression(max_iter=1000, random_state=42)

In [100]:
#model.fit(X_train, y_train)

In [101]:
print(type(X_train))

<class 'numpy.ndarray'>


In [104]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from itertools import combinations
import pandas as pd

# 사용할 전체 피처 목록
features = ['pclass', 'sex', 'age', 'fare', 'embarked', 'alone','family_size']

results = []

pd.set_option('display.max_colwidth', None) # 전체 출력 설정


# 피처 조합
for r in range(2, 8):
    for combo in combinations(features, r):     # 피처들간 조합을 r의 갯수만큼 자동으로 생성
        X_train_sub = X_train[list(combo)]      # 훈련 데이터와 테스트 데이터에서 해당 열만 선택
        X_test_sub = X_test[list(combo)]

        model = LogisticRegression(max_iter=1000, random_state=42)  # 로지스틱 회귀 모델 
        model.fit(X_train_sub, y_train)                             # 학습시키기

        y_proba = model.predict_proba(X_test_sub)[:, 1]             # 생존확률 예측 및 반환[사망확률, 생존확률]
        
        score = roc_auc_score(y_test, y_proba)                      # 실제 값과 예측 확률을 비교해서 ROC-AUC 점수계산

        results.append({'features': combo, 'roc_auc': round(score, 3)}) # 점수 저장

# 결과를 데이터프레임으로 보기
df_results = pd.DataFrame(results).sort_values(by='roc_auc', ascending=False).reset_index(drop=True)
df_results.head(10)



features  roc_auc
0               (pclass, sex, age, fare, embarked, alone)    0.885
1  (pclass, sex, age, fare, embarked, alone, family_size)    0.884
2        (pclass, sex, age, embarked, alone, family_size)    0.884
3            (pclass, sex, age, fare, alone, family_size)    0.884
4                     (pclass, sex, age, embarked, alone)    0.884
5                      (pclass, sex, age, fare, embarked)    0.884
6                   (pclass, sex, age, fare, family_size)    0.883
7                            (pclass, sex, age, embarked)    0.883
8                  (pclass, sex, age, alone, family_size)    0.881
9                         (pclass, sex, age, family_size)    0.881

In [106]:
from sklearn.metrics import roc_auc_score

y_proba = model.predict_proba(X_test)[:, 1]  
print(f"ROC-AUC: {roc_auc_score(y_test, y_proba):.3f}")


ROC-AUC: 0.884


In [107]:
selected_features = ['pclass', 'sex', 'age', 'fare', 'embarked', 'alone']

# 훈련/테스트 데이터에서 선택한 컬럼만 추출
X_train_sub = X_train[selected_features]
X_test_sub = X_test[selected_features]

# 모델 학습 및 평가
model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(X_train_sub, y_train)

y_proba = model.predict_proba(X_test_sub)[:, 1]
auc = roc_auc_score(y_test, y_proba)
print("선택한 컬럼:", selected_features)
print("ROC-AUC:", round(auc, 3))


선택한 컬럼: ['pclass', 'sex', 'age', 'fare', 'embarked', 'alone']
ROC-AUC: 0.885


In [ ]:
print(classification_report(y_test,y_pred))

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [110]:
print(len(X_test), len(y_test))          # 기준 길이
print(len(X_test_sub), len(y_pred))      # 방금 예측한 길이


179 179
179 30
